name: dropper
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hotkey_system: ^0.0.9
  tray_manager: ^0.2.4
  window_manager: ^0.4.2
  flutter_hooks: ^0.20.5
  collection: ^1.18.0
  gap: ^3.0.1
  hooks_riverpod: ^2.5.2
  cross_file: ^0.3.4+2
  shared_preferences: ^2.3.2
  super_drag_and_drop: ^0.8.22
  mime: ^1.0.6
  styled_widget: ^0.4.1
  riverpod_annotation: ^2.3.5
  flutter_acrylic: ^1.1.4
  hugeicons: ^0.0.7
  uuid: ^4.5.1
  super_clipboard: ^0.8.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  build_runner: ^2.4.12
  custom_lint: ^0.6.7

flutter:
  uses-material-design: true

  assets:
    - assets/
