name: dropper
description: "A new Flutter project."

version: 1.0.0+1

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hotkey_system: ^0.0.9
  tray_manager: ^0.5.1
  window_manager: ^0.5.1
  flutter_hooks: ^0.21.3+1
  collection: ^1.18.0
  gap: ^3.0.1
  hooks_riverpod: ^3.0.0
  cross_file: ^0.3.4+2
  shared_preferences: ^2.3.2
  super_drag_and_drop: ^0.9.1
  mime: ^2.0.0
  styled_widget: ^0.4.1
  riverpod_annotation: ^3.0.0
  flutter_acrylic: ^1.1.4
  hugeicons: ^1.0.2
  uuid: ^4.5.1
  super_clipboard: ^0.9.1
  super_context_menu: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0
  build_runner: ^2.4.12
  custom_lint: ^0.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
